account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "account"
urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='user_logout'),
    path('register/', views.register, name='user_register'),
    path('password-change/', auth_views.PasswordChangeView.as_view(template_name="account/password_change_form.html", success_url="/account/password-change-done/"), name='password_change'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name="account/password_change_done.html"), name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset_form.html", email_template_name="account/password_reset_email.html", success_url='/account/password-reset-done/'), name='password_reset'),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name="account/password_reset_done.html"), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset_confirm.html", success_url='/account/password-reset-complete/'), name="password_reset_confirm"),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), name='password_reset_complete'),
    path('my-information/', views.myself, name="my_information"),
    path('edit-my-information/', views.myself_edit, name="edit_my_information"),
    path('my-image/', views.my_image, name="my_image"),
    path('home/',auth_views.TemplateView.as_view(template_name='home.html'), name ='gotohome')
]

core/urls.py
from django.urls import path
from . import views


app_name = 'core'

urlpatterns = [
    path('index/', views.index, name="index"),

    path('download_pdf/', views.download_pdf, name="download_pdf"),
    path('after/', views.after, name="after"),
    ]

untitled6/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('core/', include('core.urls', namespace='core')),
    path('home/', TemplateView.as_view(template_name="home.html"), name='home'),
    path('captcha/', include('captcha.urls')),
    path('account/',include('social_django.urls',namespace='social')),
    path('',TemplateView.as_view(template_name="welcome.html"),name='welcome')
]

core/models.py
from django.db import models
from django.contrib.auth.models import User

class AuthorInfo(models.Model):
    title_ch = models.CharField(max_length=100, blank=True)
    title_en = models.CharField(max_length=100, blank=True)
    xueyuan = models.CharField(max_length=100, blank=True)
    zhuanye = models.CharField(max_length=100, blank=True)
    xuehao = models.CharField(max_length=100, blank=True)
    name = models.CharField(max_length=100, blank=True)
    laoshi = models.CharField(max_length=100, blank=True)
    riqi = models.DateField()
    outputname = models.CharField(max_length=100,blank=True)


class AbstractInfo(models.Model):
    keyword_ch = models.CharField(max_length=100,blank=True)
    abstract_ch = models.TextField(max_length=2000,blank=True)

    keyword_en = models.CharField(max_length=100,blank=True)
    abstract_en = models.TextField(max_length=2000,blank=True)
    wendang = models.FileField(upload_to='')



class PaperAfter(models.Model):
    bibliography = models.TextField(max_length=1000,blank=True)
    acknowledgment = models.TextField(max_length=1000,blank=True)

core/forms.py
from django import forms
from .models import AuthorInfo,PaperAfter,AbstractInfo


class AuthorForm(forms.ModelForm):
    class Meta:
        model = AuthorInfo
        fields = "__all__"

class AfterForm(forms.ModelForm):
    class Meta:
        model = PaperAfter
        fields = '__all__'


class AbstractForm(forms.ModelForm):
    class Meta:
        model = AbstractInfo
        fields = "__all__"

core/views.py
import datetime

from django.core.cache import cache

from .zhengwen import zhengwen_fix
from django.http import HttpResponse, FileResponse
from django.shortcuts import render
from .forms import AuthorForm,AfterForm,AbstractForm
import os
from .makeword import add_dict, final

from reportlab.pdfgen import canvas
from docx2pdf import convert
# Create your views here.



def index(request):
    if request.method == "POST":
        author_form = AuthorForm(request.POST)
        abstract_form = AbstractForm()
        if author_form.is_valid():
            sum_dict = {}
            dict_result1 = add_dict(dict(request.POST),sum_dict)
            cache.set('dict',dict_result1)
            cache.set('filename',request.POST['outputname'])


            print(dict_result1)

            author_form.save()

            return render(request, 'core/abstract.html', {"abstract_form":abstract_form, })
        else:
            return render(request,'core/error.html',{'form':author_form})
    else:
        author_form = AuthorForm(request.POST)
        return render(request, "core/index.html", {"form": author_form})

def after(request):
    if request.method == "POST":
        after_form = AfterForm()
        abstract_form = AbstractForm(request.POST, request.FILES)
        if  abstract_form.is_valid():
            abstract_form.save()
            dict_second =  cache.get('dict')
            dict_result2 =  add_dict(dict(request.POST), dict_second)
            cache.set('dict',dict_result2)
            cache.set('up_name', request.FILES['wendang'].name)

            print(dict_result2)
            return render(request, "core/after.html", {"after_form": after_form})
        else:
            return  render(request, "core/download.html", )

#基本成功
def download_pdf(request):
    dict_third = cache.get('dict')
    dict_result3 = add_dict(dict(request.POST), dict_third)
    cache.set('dict', dict_result3)
    print(dict_result3)

    name = cache.get('filename')
    up_name = cache.get('up_name')
    zhengwen_fix(up_name)
    print(name)
    final(dict_result3,name,up_name)
    file = open('static/pdfresult/'+name+'.docx', 'rb')
    response = FileResponse(file)
    response['Content-Type'] = 'application/octet-stream'
    response['Content-Disposition'] = 'attachment;filename =result.docx'
    return response

templates/core/abstract.html
{% extends "base.html" %}

{% load static %}

{% block title %}输入中英文摘要{% endblock %}

{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>请输入中英文摘要</h1>

    <form class="form-horizontal" action="{% url 'core:after' %}"  enctype="multipart/form-data" method="post" >{% csrf_token %}
        <div class="form-group">

            <label for="{{ abstract_form.keyword_ch.id_for_label }}" class="col-md-5 control-label">中文关键字</label>

            <div class="col-md-6 text-left">{{ abstract_form.keyword_ch }}</div>
        </div>


        <div class="form-group">

            <label for="{{ abstract_form.abstract_ch.id_for_label }}" class="col-md-5 control-label"> 中文摘要</label>
            <div class="col-md-6 text-left">{{ abstract_form.abstract_ch }}</div>
        </div>
        <div class="form-group">

            <label for="{{ abstract_form.keyword_en.id_for_label }}" class="col-md-5 control-label"> English Keywords</label>
            <div class="col-md-6 text-left">{{ abstract_form.keyword_en }}</div>
        </div>


        <div class="form-group">

            <label for="{{ abstract_form.abstract_en.id_for_label }}" class="col-md-5 control-label"> English Abstract</label>
            <div class="col-md-6 text-left">{{ abstract_form.abstract_en }}</div>
        </div>

        <div class="form-group">

            <label for="{{ abstract_form.wendang.id_for_label }}" class="col-md-5 control-label"> 请提交正文文档</label>
            <div class="col-md-6 text-left">{{ abstract_form.wendang }}</div>
        </div>

            <input type="submit" class="btn btn-primary btn-lg" value="下一步">
 </form>


</div>


{% endblock %}

templates/core/after.html
{% extends "base.html" %}

{% load static %}

{% block title %}输入参考文献及致谢{% endblock %}

{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>请输入输入参考文献及致谢</h1>

    <form class="form-horizontal" action="{% url 'core:download_pdf' %}" method="post" >
        {% csrf_token %}
        <div class="form-group">

            <label for="{{ after_form.bibliography.id_for_label }}" class="col-md-5 control-label">参考文献</label>

            <div class="col-md-6 text-left">{{ after_form.bibliography }}</div>
        </div>


        <div class="form-group">

            <label for="{{ after_form.acknowledgment.id_for_label }}" class="col-md-5 control-label"> 致谢</label>
            <div class="col-md-6 text-left">{{ after_form.acknowledgment }}</div>
        </div>
        <input type="submit" class="btn btn-primary btn-lg" value="下载文档">
 </form>
<button class="btn btn-primary btn-lg"  onclick="window.location.href='http://127.0.0.1:8000/core/index/'">返回首页继续提交</button>

</div>


{% endblock %}

templates/core/download.html
{% extends "base.html" %}

{% load static %}
{% block title %}Home page{% endblock %}
{% block content %}
{% for field in abstract_form %}



            {{ field.errors }}
            {{ field.label_tag }}: {{ field }}


{% endfor %}



{% endblock %}

templates/core/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="row text-center vertical-middle-sm">
    <h1>输入信息</h1>
    <form class="form-horizontal" action="."  enctype="multipart/form-data" method="post" >{% csrf_token %}
        <div class="form-group">
            {{ form.title_ch.errors }}
            <label for="{{ form.title_ch.id_for_label }}" class="col-md-5 control-label">
中文标题</label>
            <div class="col-md-6 text-left">{{ form.title_ch }}</div>
        </div>

        <div class="form-group">
            {{ form.title_en.errors }}
            <label for="{{ form.title_en.id_for_label }}" class="col-md-5 control-label"> 英文标题</label>
            <div class="col-md-6 text-left">{{ form.title_en }}</div>
        </div>

        <div class="form-group">
            {{ form.xueyuan.errors }}
            <label for="{{ form.xueyuan.id_for_label }}" class="col-md-5 control-label">
学院</label>
            <div class="col-md-6 text-left">{{ form.xueyuan }}</div>
        </div>

        <div class="form-group">
             {{ form.zhuanye.errors }}
            <label for="{{ form.zhuanye.id_for_label }}" class="col-md-5 control-label"> 专业</label>
            <div class="col-md-6 text-left">{{ form.zhuanye }}</div>
        </div>

        <div class="form-group">
             {{ form.xuehao.errors }}
            <label for="{{ form.xuehao.id_for_label }}" class="col-md-5 control-label"> 学号</label>
            <div class="col-md-6 text-left">{{ form.xuehao }}</div>
        </div>

        <div class="form-group">
             {{ form.name.errors }}
            <label for="{{ form.name.id_for_label }}" class="col-md-5 control-label">名字</label>
            <div class="col-md-6 text-left">{{ form.name }}</div>
        </div>

        <div class="form-group">
             {{ form.laoshi.errors }}
            <label for="{{ form.laoshi.id_for_label }}" class="col-md-5 control-label">老师</label>
            <div class="col-md-6 text-left">{{ form.laoshi }}</div>
        </div>

        <div class="form-group">
            {{ form.riqi.errors }}
            <label for="{{ form.riqi.id_for_label }}" class="col-md-5 control-label">日期</label>
            <div class="col-md-6 text-left">{{ form.riqi }}</div>
        </div>

        <div class="form-group">
            {{ form.wendang.errors }}
            <label for="{{ form.wendang.id_for_label }}" class="col-md-5 control-label">正文文档</label>
            <div class="col-md-6 text-left">{{ form.wendang }}</div>
        </div>
        <input type="submit" class="btn btn-primary btn-lg" value="提交">
    </form>
</div>

</body>
</html>

templates/core/index.html
{% extends "base.html" %}

{% load static %}

{% block title %}输入信息{% endblock %}

{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>输入信息</h1>
    <form class="form-horizontal" action="."  enctype="multipart/form-data" method="post" >{% csrf_token %}
        <div class="form-group">

            <label for="{{ form.title_ch.id_for_label }}" class="col-md-5 control-label">中文标题</label>
            <div class="col-md-6 text-left">{{ form.title_ch }}</div>
        </div>

        <div class="form-group">

            <label for="{{ form.title_en.id_for_label }}" class="col-md-5 control-label"> 英文标题</label>
            <div class="col-md-6 text-left">{{ form.title_en }}</div>
        </div>

        <div class="form-group">

            <label for="{{ form.xueyuan.id_for_label }}" class="col-md-5 control-label">学院</label>
            <div class="col-md-6 text-left">{{ form.xueyuan }}</div>
        </div>

        <div class="form-group">

            <label for="{{ form.zhuanye.id_for_label }}" class="col-md-5 control-label"> 专业</label>
            <div class="col-md-6 text-left">{{ form.zhuanye }}</div>
        </div>

        <div class="form-group">

            <label for="{{ form.xuehao.id_for_label }}" class="col-md-5 control-label"> 学号</label>
            <div class="col-md-6 text-left">{{ form.xuehao }}</div>
        </div>

        <div class="form-group">

            <label for="{{ form.name.id_for_label }}" class="col-md-5 control-label">名字</label>
            <div class="col-md-6 text-left">{{ form.name }}</div>
        </div>

        <div class="form-group">

            <label for="{{ form.laoshi.id_for_label }}" class="col-md-5 control-label">老师</label>
            <div class="col-md-6 text-left">{{ form.laoshi }}</div>
        </div>

        <div class="form-group">

            <label for="{{ form.riqi.id_for_label }}" class="col-md-5 control-label">日期</label>
            <div class="col-md-6 text-left">{{ form.riqi }}</div>
        </div>
         <div class="form-group">

            <label for="{{ form.outputname.id_for_label }}" class="col-md-5 control-label">输出文件名</label>
            <div class="col-md-6 text-left">{{ form.outputname }}</div>
        </div>

        <input type="submit" class="btn btn-primary btn-lg" value="下一步">
    </form>
</div>


{% endblock %}

templates/core/pageJump.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<p>提交成功！还有<span id="sp">5</span>秒跳转到登录界面...</p>
<script>
    onload=function () {
        setInterval(go,1000)
    };
    var x=4;
    function go() {

        if (x>=0){
            document.getElementById("sp").innerText=x;
        }else {
            location.href="{% url 'account:user_login' %}";
        }
        x--;
    }
</script>



</body>
</html>

templates/core/pageJump_to_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>登录失败还有<span id="sp">5</span>秒跳转回登录界面...</h1>
<p>请检查你的登录信息并重试</p>
<script>
    onload=function () {
        setInterval(go,1000)
    };
    var x=4;
    function go() {

        if (x>=0){
            document.getElementById("sp").innerText=x;
        }else {
            location.href="{% url 'account:user_login' %}";
        }
        x--;
    }
</script>



</body>
</html>