account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "account"
urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='user_logout'),
    path('register/', views.register, name='user_register'),
    path('password-change/', auth_views.PasswordChangeView.as_view(template_name="account/password_change_form.html", success_url="/account/password-change-done/"), name='password_change'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name="account/password_change_done.html"), name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset_form.html", email_template_name="account/password_reset_email.html", success_url='/account/password-reset-done/'), name='password_reset'),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name="account/password_reset_done.html"), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset_confirm.html", success_url='/account/password-reset-complete/'), name="password_reset_confirm"),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), name='password_reset_complete'),
    path('my-information/', views.myself, name="my_information"),
    path('edit-my-information/', views.myself_edit, name="edit_my_information"),
    path('my-image/', views.my_image, name="my_image"),
    path('home/',auth_views.TemplateView.as_view(template_name='home.html'), name ='gotohome')
]

core/urls.py
from django.urls import path
from . import views


app_name = 'core'

urlpatterns = [
    path('index/', views.index, name="index"),

    path('download_pdf/', views.download_pdf, name="download_pdf"),
    path('after/', views.after, name="after"),
    ]

untitled6/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('core/', include('core.urls', namespace='core')),
    path('home/', TemplateView.as_view(template_name="home.html"), name='home'),
    path('captcha/', include('captcha.urls')),
    path('account/',include('social_django.urls',namespace='social')),
    path('',TemplateView.as_view(template_name="welcome.html"),name='welcome')
]

templates/base.html
{% load static %} <!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
    <body>
        {% include "header.html" %} 
        <div class="container">
            {% block content %}
            {% endblock %} 
        </div>
        {% include "footer.html" %}
        {% block javascript %}
        {% endblock %} 
    </body>
</html>

templates/footer.html
<div class="container"> <hr>
    <p class="text-center">copy right 信息科学与技术学院</p>
</div>

templates/header.html
{% load static %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation"> 
        <div class="navbar-header">
            <img src="{% static 'images/std.jpg' %}"  height="50px" width="50px">

        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'home' %}">HOME</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right:10px"> 
                {% if user.is_authenticated %}
                    <li>
                    <div class="navbar-header">
                    </div>
                    </li>
                <li>
                    <div class="dropdown" style="margin-top:8px">
                        <button class='btn btn-default dropdown-toggle' type='button' id='dropdownMenu' data-toggle='dropdown'>{{ user.username }}
                            <span class='caret'></span> 
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                            <li><a href="{% url 'account:my_information' %}">个人信息</a></li>
                        </ul> 
                    </div>
                </li>
                <li><a href="{% url 'account:user_logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'account:user_login' %}">LOGIN</a></li> 
                <li><a href="{% url 'account:user_register' %}">Sign up</a></li>
                {% endif %}
            </ul> 
        </div>

    </nav>
</div>

<script src="{% static 'js/jquery.js' %}"></script> 
<script src="{% static 'js/bootstrap.js' %}"></script>

templates/home.html
{% extends "base.html" %}

{% load static %}
{% block title %}Home page{% endblock %}
{% block content %}

<div class="row  vertical-middle-sm">

    <h1>点击按钮进入系统</h1>
    <a href="{% url 'core:index' %}">点我</a>




</div>


{% endblock %}

templates/paginator.html
<div class="pagination"> 
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a> 
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }} 
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a> {% endif %}
    </span>
</div>
    

templates/welcome.html
{% extends "base.html" %}

{% load static %}
{% block title %}欢迎页{% endblock %}
{% block content %}

<div class="row  vertical-middle-sm">

    <h1>点击按钮开始登录</h1>
    <a href="{% url 'account:user_login' %}">点我</a>




</div>


{% endblock %}